### ISSUE TITLE
Sort websites by SLD

### ISSUE THREAD

**Issue by geek-merlin** [freistil/dashboard-issues#106]
As a user i want to see my websites by second level domain of hostname (so *.foo.com and *.bar.com):

- ...
- dev.bar.com
- test.bar.com
- www.bar.com
- foo.com
- dev.foo.com
- test.foo.com
- ...

Currently it's a holy mess and websites of the same project are spread all over the place:

- ...
- dev.bar.com
- dev.foo.com
- dewanda.com
- duda.com
- dudeldu.com
- foo.com
- test.bar.com
- test.foo.com
- www.bar.com
- ...

Implementing this as a reverse lexical sorting scheme will make this work also for domains where third level is relevant like foo.com.au.

**Comment by geewiz** [comment]
Yup, makes sense. Thanks, Axel!

**Comment by geewiz** [comment]
This issue was moved to freistil/dashboard_api#382
