### ISSUE TITLE
Spaces in environment names should not be allowed

### ISSUE THREAD

**Issue by gihuphil** [freistil/dashboard-issues#107]
One of our customers called his deplyoment environment "Testumgebung Nicolai". This leads to:

SetEnv SITEENV Testumgebung Nicolai

This is not valid as SetEnv accepts a maximum of 2 arguments. The effect is that the syntaxcheck prior to restart / reload fails and no more changes to the configuration are taken in effect.

We really should do some input validation in the forms to make sure we do not accept input that renders the webserver unusable. The same pitfall we have with Domainnames, if onvalid Hostnames are entered the same effect can be seen. See also here:

https://app.intercom.io/a/apps/qvgr5r28/respond/inbox/conversation/12212612505

**Comment by geewiz** [comment]
We have to add an validation to prevent this. (We do have host name validation already, though.)

**Comment by geewiz** [comment]
This issue was moved to freistil/dashboard_api#383
