### ISSUE TITLE
Set default number of websites for a new cluster to 3

### ISSUE THREAD

**Issue by gihuphil** [freistil/dashboard-issues#112]
Currently, when we create a new cluster in the dashboard its website limit is 0, which means unlimited. As we currently build new freistilbox clusters as solo, we need to think of setting this one to three according to our hosting plan for freistilbox solo. This is often forgotten, hence customers paying for solo have more site capacitiy than they should have, and pay for. This makes it unlikely for many of them to switch to freistilbox pro, as solo with unlimited websites is already a quite powerful product. Please set the default value to three when a new cluster is created to avoid such situations.

**Comment by geewiz** [comment]
Good idea.

**Comment by geewiz** [comment]
This issue was moved to freistil/dashboard_api#386
