### ISSUE TITLE
Add feature to be able to configure cluster-wide ssh keys

### ISSUE THREAD

**Issue by ghost** [freistil/dashboard-issues#114]
Currently a user has to add an ssh key to each site they have configured in the dashboard.

The ability to add keys to the entire cluster that then would be deployed for all sites would be helpful fo users.

Background see:
https://app.intercom.io/a/apps/qvgr5r28/inbox/inbox/874661/conversations/14050458180

**Comment by geewiz** [comment]
This issue was moved to freistil/dashboard_api#388
