### ISSUE TITLE
Show cluster setup details

### ISSUE THREAD

**Issue by muhh** [freistil/dashboard-issues#33]
A cluster view should provide details about it's current setup.
- Cluster size (how many boxes in what size)
- Cluster public IP - see #24
- Configured SSL certificates and their respective IP addresses if SNI is not in use.
- SSH Hostname

**Comment by geewiz** [comment]
These are very different features, each with its own data and logic. Can you please split them up into separate issues so we can tackle them one at a time?

**Comment by geewiz** [comment]
This issue was moved to freistil/dashboard_api#352
