### ISSUE TITLE
REST API: fetch sites of a cluster

### ISSUE THREAD

**Issue by mkernel** [freistil/dashboard-issues#42]
Having an API to manage all freistilbox clusters one has access to would be really nice.
If we're able to fetch all clusters, the next set of information to fetch would be the list of sites of a given cluster including
- git repository
- staging environment
- main domain
- co-domains
- database credentials
- ssh keys

**Comment by geewiz** [comment]
@mkernel Since the result sets are getting considerably extensive, I've decided to switch from a custom response format to the JSON API specification (http://jsonapi.org/). You'll have to make some changes to your parser.

**Comment by geewiz** [comment]
@mkernel BTW, issue no. 42 — nice one! :-)
