### ISSUE TITLE
Hint PHPMyAdmin Access

### ISSUE THREAD

**Issue by kfrohwein** [freistil/dashboard-issues#44]
"As a developer I want a hint where I can find the phpmyadmin for a database to easily access it"

Please hin "https://db12345.freistilbox.net/pma/" in the database dropdown as a clickable link.

**Comment by geewiz** [comment]
Thanks, Karsten! I like this idea.

**Comment by benthebear** [comment]
<3

**Comment by geewiz** [comment]
This issue was moved to freistil/dashboard_api#356
