### ISSUE TITLE
No option to not create a default Database

### ISSUE THREAD

**Issue by kfrohwein** [freistil/dashboard-issues#45]
As a customer I want to create a new site without a MySQL database as I just might not need it.

---

We just created a test site that did not need a DB. Even if you waste only a few resource it might be wise to make the creation of a new DB optional in some way.

**Comment by muhh** [comment]
There is only a database created if you actively do it by clicking "Add database".

**Comment by geewiz** [comment]
Markus, obviously this isn't obvious. :-) Could this be a UI bug?

**Comment by muhh** [comment]
It would be more obvious if it would be written in plain sight that there is no database yet.

So my suggestion is: add text "no databases" in the box if there are none.

**Comment by kfrohwein** [comment]
Miscommunication on our side :)

Michael did click on "create DB" but now he can't delete it anymore... But this is another story than.

**Comment by geewiz** [comment]
So far, we've been very cautios with adding nuke buttons. ?? We'll add them over time.

Until then, simply send us a support request from the website page and we'll clean it up for you.

[--- Commented from Asana.com
#commenter Jochen Lillich
---[aa]
