### ISSUE TITLE
Test if domain names resolve in DNS

### ISSUE THREAD

**Issue by gihuphil** [freistil/dashboard-issues#64]
In [Ticket 12584](https://freistil.zendesk.com/agent/tickets/12584), there occured the situation that the customer entered a placeholder as main domain instead of the real DNS name. This resulted in an apache configuration that was unable to serve the site, because the ServerName never matched with the Host header of the request.

As far as I can see, the main domain and also redirect domain fields must always contain hostnames that either resolve to an IP address or a CNAME record, despite people sometimes enter values before they switch DNS just to see if everything works on our side. I suggest we do a simple DNS lookup on the value the customer entered and warn him if it doesn't resolve, with an explicit explanation of the consequences. Maybe we shouldn't disallow names without DNS entry as sometimes people want to configure the site on our side properly before they switch, but we should really give a hint that entering somthing senseless will result in the site not being available.

**Comment by geewiz** [comment]
I don't know if I understand you correctly. We only validate that the domain name is valid but we don't check if it actually exists as a DNS record.

**Comment by gihuphil** [comment]
The customer entered "master" as main domain, which looks like a valid hostname but took his site out of the web. In fact, most textual strings can be valid hostnames, but that doesn't help when there's no IP address associated to it.

**Comment by muhh** [comment]
For this problem we provide default server aliases, in the pattern `SITEHANDLE.CLUSTERID.freistilbox.net`. 

There seems to be no documentation on this. 

And I'd like to propose to change to topic of this issue to always show this alias name in the dashboard.

**Comment by geewiz** [comment]
I'm surprised there isn't an issue yet for displaying the default alias. And since I'm strictly against changing an issue title after there's already been a discussion whose context would be completely lost, I'll go and create one.

Since we're using a wildcard CNAME, customers can even use custom names like `example-stage.CLUSTERID.freistilbox.net`. I'll add documenting this (both in docs and Dashboard input form) to the new issue as well.

**Comment by muhh** [comment]
Agreed. 

This makes this issue obsolete, right?

**Comment by geewiz** [comment]
I do think so.
