### ISSUE TITLE
Make setup of redis services easier

### ISSUE THREAD

**Issue by gihuphil** [freistil/dashboard-issues#85]
When setting up a redis service in the dashboard, one has to select the website it is for. Currently, this is a unsorted list containing all main domains, this is just like seeking a needle in a haystack. ;) Is it possible to make this field either sorted or a free text input form? That would save lots of time and nerves.

**Comment by geewiz** [comment]
I agree. This needs to be a part of #53.

**Comment by geewiz** [comment]
This issue was moved to freistil/dashboard_api#371
