### ISSUE TITLE
Display Edge Router IP for each website

### ISSUE THREAD

**Issue by geewiz** [freistil/dashboard-issues#9]
"As a user, I want to see the Edge Router IP address for each website so I can configure the DNS accordingly."

**Comment by kplanz** [comment]
Would also be nice if one could see the IP of the web server and the shell host :)

**Comment by geewiz** [comment]
@kplanz The shell host now gets displayed with a full `ssh` command: http://d.pr/i/RtTn

**Comment by geewiz** [comment]
@kplanz On freistilbox, there's no "the web server" — every website runs on a number of application boxes behind the Edge Router and Content Cache.

**Comment by kplanz** [comment]
@geewiz Alright, makes sense.

**Comment by geek-merlin** [comment]
This would help. Last night again i routed to the shell box...
Of course a cname rather than an IP might make more sense.

**Comment by geewiz** [comment]
There actually is a CNAME as documented here: http://www.freistilbox.com/docs/dns.html

Still, nothing beats having it displayed in the Dashboard.

**Comment by derhasi** [comment]
What's the status on this?
Every time I am unsure of what IP to use, especially as there is a different IP for https enabled sites.

**Comment by geewiz** [comment]
Hi Johannes, thanks for bringing this up again! I went and added this issue to our Business Projects list. Our prioritisation formula catapulted it up right to rank 4, so expect this to be implemented shortly. 

I've now assigned this issue to a new milestone that you can track as well.

**Comment by geewiz** [comment]
I'm happy to report that this feature has finally been implemented and is current in staging. 🙂
